source "http://rubygems.org"

# git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'capybara'
gem "cucumber"
gem "faker"
gem "ffi"
gem "httparty"
gem "rspec"
gem "selenium-webdriver"
gem "site_prism"